### PR TITLE
GCI Task - Improving Code Readability

### PR DESCRIPTION
**Pull request by DeeprajPandey**
Hope the request will be merged ASAP. :)

### CODE REVIEW

**Comment by DeeprajPandey** [comment]
Hi!
For some reason, the task has disappeared from the GCI Task list. :/

**Comment by canihavesomecoffee** [comment]
If you didn't claim the task yet, it's possible the number of instances have all been taken.

**Comment by DeeprajPandey** [comment]
Hi @canihavesomecoffee the task reappeared. But I don't seem to get where the check is failing.
Can you help me, please?

**Comment by canihavesomecoffee** [comment]
That's just fine. If you look at the test status of the last commit, you'll see it also "fails" on the same file.

**Pull request closed without merging**
