### PR TITLE
Add SCC support for CEA-708 Decoder

### PR DESCRIPTION
**Pull request by voidash**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.
- [x] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [x] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

---
When SCC was extracted from MOV file, the `SCC` file was empty. So in order to fix that this pull request is being made. The exact issue it fixes is #1426 .Now SCC can be extracted from the sample video provided in the issue. Also It might be worth mentioning that the SCC caption type is pop on.

### CODE REVIEW

**Comment by PunitLodha** [comment]
Please fix the formatting issues by running clang-format and rustfmt

**Comment by ArchitBhonsle** [comment]
Any idea why this PR isn't merged? Is there some work left?

**Comment by cfsmp3** [comment]
> Any idea why this PR isn't merged? Is there some work left?

If I remember correctly, @voidash disappeared

**Comment by PunitLodha** [comment]
> Any idea why this PR isn't merged? Is there some work left?

@ArchitBhonsle If you test this PR, you'll see that the SCC header is being repeated for each subtitle line

**Comment by cfsmp3** [comment]
Closing since @voidash seems to have vanished and there's merge conflicts and @IshanGrover2004 has been working on this anyway.

**Pull request closed without merging**
