### PR TITLE
[FIX] Correctly handle return codes.

### PR DESCRIPTION
**Pull request by saurabhshri**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [x] I am an active contributor to CCExtractor.

---
Return code after parameter parsing were incorrectly handles leading to errors such as `Error: Invalid option to CCextractor Library` when the program should not have continues et cetera.

### CODE REVIEW

**Comment by saurabhshri** [comment]
@cfsmp3 I used Github-Web to resolve the conflict and looks like it changed the indentation. 

@techfreakworm After your commit, the code style appears to be changed. There are mixed code style and indentation all over the place. Please look into it and also remove all the comments that should not be present in upstream. E.g. (https://github.com/CCExtractor/ccextractor/blob/master/src/ccextractor.c#L562) :)

**Comment by techfreakworm** [comment]
@saurabhshri how did that happen? I just changed one file Makefile.am, and neither git notified me of the changes of other files.. 
And as far as I remember I never edited core source of CCExtractor. Not even while earning Gsoc points. Are you sure it happened because of my last commit?

**Comment by saurabhshri** [comment]
@techfreakworm I am really sorry, I tagged you by mistake. That comment was meant for @Diptanshu8 :)

**Comment by techfreakworm** [comment]
@saurabhshri aah.. No problem. :)

**Pull request merged**
