### PR TITLE
Added --forceflush (-ff) option

### LINKED ISSUE #306: Add --forceflush (-ff) as parameter
An easy one for GSoC applicants:

We need to add a parameter --forceflush (short -ff) that if used will cause the file buffers to be flushed as soon as content is written.

Actually the functionality itself is already there 
(file ccx_encoders_common.c, check the call to fsync)

but currently it's forced. The required change implies is that only if forceflush is used fysnc is to be called.

### PR DESCRIPTION
**Pull request by Aesmade**
Added option for forcing a flush on the output buffer whenever content is written

### CODE REVIEW

**Comment by Aesmade** [comment]
@ccx-testerbot runtests master

**Comment by canihavesomecoffee** [comment]
@ccx-testerbot runtests master

@Aesmade I'll run them for you :)

**Comment by anshul1912** [comment]
you are changing the default behaviour of ccextractor, now we only force the buffer if -ff option is passed. you are trying to make it optional, may I know the use case, where you find force buffer is not useful and create problem for you.

**Comment by canihavesomecoffee** [comment]
@anshul1912: It was requested by @cfsmp3, because when he added it it slows down CCExtractor (or at least the bot test run) with 100%, hence his request in #306 to make it optional again

**Pull request merged**
