### PR TITLE
Cleanup vs configs

### PR DESCRIPTION
**Pull request by canihavesomecoffee**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.
- [x] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [x] I am an active contributor to CCExtractor.

---

Reduces the amount of VS configs to 2 (64 bit OCR enabled debug and release), cleans up the Nuklear GUI from the repo, build Rust in the correct mode (release or debug) depending on the build.

### CODE REVIEW

**Review by cfsmp3 — APPROVED** [review]
Some spring cleaning is always nice

**Review by cfsmp3 — APPROVED** [review]
Some spring cleaning is always nice

**Review by PunitLodha — APPROVED** [review]
You could also remove `windows/rustx86.bat`, as its not being used anymore

**Comment by prateekmedia** [comment]
@canihavesomecoffee is there any blocker for this PR, if not why haven't it been merged already?

**Pull request merged**
