### PR TITLE
Fixes #304

### LINKED ISSUE #304: Premature end of file.
File Link: https://drive.google.com/open?id=0B5-K4mJ0WYBTeEN6ZWFDV2lIbUk
When ccextractor is executed on this file, it is giving result as "Premature end of file". Because of that the appropriate .srt file is not created. 
On running the same on vlc, closed captions are coming flawlessly.

I think, it shouldn't matter whether the video file is cut or not, ccextractor should give the relevant cc.

### PR DESCRIPTION
**Pull request by at25sep**

### CODE REVIEW

**Comment by at25sep** [comment]
@canihavesomecoffee  Can you please run tests on this?

**Comment by canihavesomecoffee** [comment]
@ccx-testerbot runtests master

**Comment by canihavesomecoffee** [comment]
DVB/5.mpg	-codec dvbsub -out=spupng looks broken.

**Comment by at25sep** [comment]
@canihavesomecoffee  can you please run test again on this?
Is there any other file broken?

**Comment by canihavesomecoffee** [comment]
@ccx-testerbot runtests master

**Comment by canihavesomecoffee** [comment]
Looks like there's no more obvious errors now.

**Comment by abhishek-vinjamoori** [comment]
@ccx-testerbot runtests master

**Pull request closed without merging**
