### PR TITLE
updated gpac lib

### PR DESCRIPTION
**Pull request by tejasdhole**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.
- [ ] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [x] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

---

{pull request content here}

### CODE REVIEW

**Comment by tejasdhole** [comment]
I have add new gpac lib version which is GPAC 2.2
 released on Dec 19, 2022

**Comment by cfsmp3** [comment]
> I have add new gpac lib version which is GPAC 2.2
>  released on Dec 19, 2022
> 

Does its actually build and work?

**Comment by tejasdhole** [comment]
@cfsmp3 how do i cheak if wheather my pull request is build and work ,is their any testing method from my side 


> > I have add new gpac lib version which is GPAC 2.2
> > released on Dec 19, 2022
> 
> Does its actually build and work?

i'd check on their official website they have released it ,but didn't check if its working on project or not

**Comment by cfsmp3** [comment]
> 
> @cfsmp3 how do i cheak if wheather my pull request is build and work ,is their any testing method from my side 
> 

You need to build the project locally at least and actually test.

Please don't send untested PRs, if we just needed to copy files we could do it ourselves.

**Pull request closed without merging**
