### PR TITLE
Fixed multiple spelling mistakes

### PR DESCRIPTION
**Pull request by ManveerBasra**

### CODE REVIEW

**Comment by grave-w-grave** [comment]
my British English self cries at the correction of British English to American Englishes :(

**Comment by ManveerBasra** [comment]
Oh, I'm sorry if I did that. I didn't mean to tbh, I just thought that was
how it was spelled. If you want me to change them back, let me know which
ones they are and I'll do it tomorrow.

**Comment by cfsmp3** [comment]
This is a general thing - doesn't have a good solution, one side of the
Atlantic will be unhappy :-)
So for official acronyms like OCR we use whatever the official spelling is,
which I assume depends on who invented it.
For words that are not correctly written in either variant whoever fixes it
can use the variant they want.
Words that are correct in one variant are not changed.
Yes, this leads to having both British English and American English mixed
in the code, but if they can do it in TV shows all the time so can we,
being a TV show centric software.

**Comment by anshul1912** [comment]
Can you remove British to American change from your pull request to get it merged.

**Pull request merged**
