### PR TITLE
removing some global and static variable.

### PR DESCRIPTION
**Pull request by anshul1912**
@ccx-testerbot runtests

### CODE REVIEW

**Comment by anshul1912** [comment]
@ccx-testerbot runtests

**Comment by anshul1912** [comment]
@ccx-testerbot runtests

**Comment by anshul1912** [comment]
@ccx-testerbot runtests

**Comment by anshul1912** [comment]
@ccx-testerbot runtests

**Comment by anshul1912** [comment]
@ccx-testerbot runtests

**Comment by anshul1912** [comment]
@ccx-testerbot runtests

**Comment by anshul1912** [comment]
I have  tested this Pull request locally on server using Willem Test suite, this request does not break anything

**Comment by canihavesomecoffee** [comment]
@ccx-testerbot runtests

**Comment by canihavesomecoffee** [comment]
@ccx-testerbot runtests

**Pull request merged**
