### PR TITLE
[FEATURE] Create linux AppImage for building CCExtractor

### PR DESCRIPTION
**Pull request by IshanGrover2004**
**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [ ] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [ ] I give this submission freely, and claim no ownership to its content.
- [ ] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [x] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

Addresses Issue #1348 

What I did (Current state):
- Replace non-working link
- Replace not working or irrelevant commands
- All library which are required in gcc command are installed correctly
- To compile the ccextractor with all static libraries, we need to have correct `configure.ac` and `Makefile.am` file (currently its giving error, maybe I am doing anything wrong [here](https://github.com/IshanGrover2004/ccextractor-fork/blob/6f70cdbf452a5b4f1f1158062d2b5dba54d27fe7/linux/build-static.sh#L117))

Goal for now:
- Compiling and make `ccextracter` binary file(which is required while making `AppImage`)

Code breaks at:
- When it clones ccextracter and try to run `make` command([here](https://github.com/IshanGrover2004/ccextractor-fork/blob/6f70cdbf452a5b4f1f1158062d2b5dba54d27fe7/linux/build-static.sh#L117)).

### CODE REVIEW

**Comment by IshanGrover2004** [comment]
I am using these commands([link](https://github.com/IshanGrover2004/ccextractor-fork/blob/6f70cdbf452a5b4f1f1158062d2b5dba54d27fe7/linux/build-static.sh#L117)):
```sh
autoreconf --install
./configure --without-rust
make ENABLE_OCR=yes
```
which gives error:
```c
In file included from ../src/lib_ccx/params.c:13:
../src/lib_ccx/compile_info.h:7:10: fatal error: compile_info_real.h: No such file or directory
    7 | #include "compile_info_real.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:3073: ../src/lib_ccx/ccextractor-params.o] Error 1
```
I wanted to confirm, am I doing this correct?

**Comment by prateekmedia** [comment]
@IshanGrover2004 is it working yet? Or are you still stuck with the error

**Comment by IshanGrover2004** [comment]
> Is it working yet? Or are you still stuck with the error

Stuck with the error

**Comment by prateekmedia** [comment]
Maybe alpine and docker are causing this, are you sure this is the right way to build AppImage? There's also appimagetool used to build it.

**Comment by canihavesomecoffee** [comment]
You're not running the pre-build.sh script that generates that header file ;)

**Comment by IshanGrover2004** [comment]
> Maybe alpine and docker are causing this, are you sure this is the right way to build AppImage? There's also appimagetool used for building it.

Currently my goal is to get ccextractor binary file which should statically linked then i will attach that binary file in AppImage
For more info read PR discription.

**Comment by IshanGrover2004** [comment]
> You're not running the pre-build.sh script that generates that header file ;)
> 
> (or using cmake; https://github.com/CCExtractor/ccextractor/commit/4fe82abbfcb61f90cf542bb3ebf0e3702782140e)

Okk, I'll try this.
Can you have a look [here](https://github.com/IshanGrover2004/ccextractor-fork/blob/6f70cdbf452a5b4f1f1158062d2b5dba54d27fe7/linux/build-static.sh#L117), is this the right way or should i have to change anything

**Comment by IshanGrover2004** [comment]
> You're not running the pre-build.sh script that generates that header file ;)

Yeah that fixed it (I used `autogen.sh`)

From past few days, I tried many thing to fix this script and I am just stuck with the
```bash
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lgpac: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:1811: ccextractor] Error 1
```
I did build libgpac from source and i able to run `gcc temp.c -lgpac` and i can see the binaries installed(at /usr/local/lib/ & ...)

**Comment by prateekmedia** [comment]
@IshanGrover2004 have you installed libgpac on your system or you are installing it in the alpine linux under this script?

**Comment by IshanGrover2004** [comment]
> @IshanGrover2004 have you installed libgpac on your system or you are installing it in the alpine linux under this script?

I am installing in alpine linux in docker

It is failing in mine as well (I use Arch)
```bash
/usr/bin/ld: cannot find -lgpac: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:1811: ccextractor] Error 1
```

**Comment by prateekmedia** [comment]
@IshanGrover2004 The alpine and docker method may have some outdated steps, if you really want to build AppImage I would suggest to use this package:
https://github.com/AppImageCrafters/appimage-builder

This will help you write for ubuntu or other distro and write recipe and generate AppImage.

**Comment by IshanGrover2004** [comment]
> if you really want to build AppImage I would suggest to use this package: https://github.com/AppImageCrafters/appimage-builder

@prateekmedia  Still we want to have first `ccextractor` executable bin file which should be statically linked
And there is where problem occurs

**Comment by prateekmedia** [comment]
I am able to build already, I think you should refer to this:
https://github.com/CCExtractor/ccextractor/wiki/Installation#linux

and 

https://github.com/CCExtractor/ccextractor/blob/master/docs/COMPILATION.MD

**Comment by IshanGrover2004** [comment]
> I am able to build already, I think you should refer to this: https://github.com/CCExtractor/ccextractor/wiki/Installation#linux
> 
> and
> 
> https://github.com/CCExtractor/ccextractor/blob/master/docs/COMPILATION.MD

I am already aware of these resources, this will result a binary which is dynamic linked(you can check by `ldd <binary>`)
but we need to perform **static** build & that is what I am trying to do by 
```sh
git clone https://github.com/CCExtractor/ccextractor
cd ccextractor/linux/
perl -i -pe 's/O3 /O3 -static /' Makefile.am
set +e
./autogen.sh
./configure --without-rust
make ENABLE_OCR=yes
```

My thought process is that if somehow I can have some files(lets say a header file or obj files) which i can attach with gcc compiler to hand compile with all static(`.a`) binaries needed like [this](https://github.com/IshanGrover2004/ccextractor-fork/blob/1e669593c8b2b7d08e5da30f5d5f595b6552b488/linux/build-static.sh#L120)

Lets take a example to explain my approach:
I will install all necessary library statically(Eg. `lib1.a`, `lib2.a`) and I have some program(main.c, etc)
So to compile I can just do `gcc main.c [more program files] lib1.a lib2.a -o out`

That's why I add `obj/*` [here](https://github.com/IshanGrover2004/ccextractor-fork/blob/1e669593c8b2b7d08e5da30f5d5f595b6552b488/linux/build-static.sh#L122) by thinking if i can get obj files from C source files by `make` 
I may be very wrong so correct me @prateekmedia . And if you understand my approach so now you could tell how can i get `objs/*` kinda thing

**Comment by prateekmedia** [comment]
You should not care about dynamic or static, at the end you have to bundle the libraries with .so related to build in the appimage

**Comment by IshanGrover2004** [comment]
> You should not care about dynamic or static, at the end you have to bundle the libraries with .so related to build in the appimage

So do I need to make just AppImage(and doesn't care about static or dynamic)
Because i thought, maybe some people really care about static or dynamic build(that's why `build-static` exist)

**Comment by prateekmedia** [comment]
If you are bundling everything then nothing matters, although do remember if some system have minimum library version requirement like GLIBC 2.32 or more, then you just have to cater that.

**Comment by IshanGrover2004** [comment]
So should I change this PR to actually build AppImage for ccextractor (instead of build-static)

**Comment by prateekmedia** [comment]
You should just build and bundle libraries to AppImage and test in different ubuntu versions to check backward compatibility.

**Comment by IshanGrover2004** [comment]
> You should just build and bundle libraries to AppImage and test in different ubuntu versions to check backward compatibility.

ig [this](https://appimage-builder.readthedocs.io/en/latest/advanced/full_bundle.html#instructions) is the exactly what you want, Is it @prateekmedia ?

**Comment by prateekmedia** [comment]
> > You should just build and bundle libraries to AppImage and test in different ubuntu versions to check backward compatibility.
> 
> ig [this](https://appimage-builder.readthedocs.io/en/latest/advanced/full_bundle.html#instructions) is the exactly what you want, Is it @prateekmedia ?

Yeah, something like that.

**Comment by IshanGrover2004** [comment]
After a lot struggle with different AppImage tools, I successfully made an AppImage which is working.
@prateekmedia Do we want a script for building AppImage(currently failing somewhere but delivered working AppImage) or Just binary for the release page(most organisation do directly have link to the AppImage binary)

**Comment by IshanGrover2004** [comment]
This PR is ready to review and get merged

**Comment by prateekmedia** [comment]
@IshanGrover2004 have you tested the generated AppImage in your system and some other system without any dependency installed like in fresh Ubuntu 20.04?

**Comment by IshanGrover2004** [comment]
> @IshanGrover2004 have you tested the generated AppImage in your system and some other system without any dependency installed like in fresh Ubuntu 20.04?

This script file result AppImage when your system has necessary lib installed(able to run `cmake ../src; make;` in ccextrcator repo)
For making it system independent we have to install every library manually  and setup them in AppDir which will be ig not good idea

**Comment by prateekmedia** [comment]
@IshanGrover2004 We need to supply tessdata within AppImage, that was the purpose of this:
https://github.com/CCExtractor/ccextractor/issues/1348#issuecomment-1481494889

**Comment by prateekmedia** [comment]
Packaging library in the AppImage is needed to make it really replacement of static i.e. system independent as static libraries are packaged already.

**Comment by IshanGrover2004** [comment]
Okk let me try that as well

**Review by canihavesomecoffee — APPROVED** [review]
lgtm, it builds on my machine; seems to work with a random sample for test purposes.

We should possibly update and include this in a release build.

**Comment by IshanGrover2004** [comment]
@canihavesomecoffee  This currently build AppImage successfully but it needs improvisation, So Whenever I'll get time to update I will and once achieved open PR

**Pull request merged**
