### PR TITLE
[IMPROVEMENT] Add Cmake job to github action

### PR DESCRIPTION
**Pull request by NilsIrl**
**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [X] I have used CCExtractor just a couple of times.

---

### CODE REVIEW

**Comment by NilsIrl** [comment]
did it just build in 35 seconds?

**Comment by NilsIrl** [comment]
I'm not sure if adding `-j$(nproc)` is the correct way to parallelize.

**Comment by canihavesomecoffee** [comment]
> 
> 
> I'm not sure if adding `-j$(nproc)` is the correct way to parallelize.

I see it being used in quite some other projects, so lgtm.

**Comment by NilsIrl** [comment]
> I see it being used in quite some other projects, so lgtm.

I was thinking within a github action environment.

**Pull request merged**
