### PR TITLE
Add support for multi-packet PATs and PMTs in MPEGTS

### PR DESCRIPTION
**Pull request by brooss**
Add support for multi-packet PATs and PMTs in MPEGTS

### CODE REVIEW

**Comment by wforums** [comment]
@ccx-testerbot runtests

**Comment by wforums** [comment]
@brooss looks like most of the changes are small timing changes, but there also seem to be some first lines missing:

_Broken:
4.mpg	-autoprogram -out=ttxt -latin1 -ucla -xds
5.ts	-autoprogram -out=ttxt -latin1

_DVB:
2.ts	-autoprogram -out=srt -latin1

_General:
13.mpg	-autoprogram -out=ttxt -latin1 -ucla
15.mpg	-autoprogram -out=ttxt -latin1 -ucla
16.ts	-autoprogram -out=ttxt -latin1 -ucla
16.ts	-autoprogram -out=srt -latin1

_Teletext:
16.mpg	-autoprogram -out=ttxt -latin1 -datets
8.mpg	-autoprogram -out=ttxt -latin1
6.mpg	-autoprogram -out=ttxt -latin1
5.mpg	-autoprogram -out=ttxt -latin1

_XDS:
Probably the same, but it's a very big file...

_Options:
Closedcaption_atsc_2channel.ts -autoprogram -out=srt -latin1 -2
Closedcaption_atsc_endCredits.ts	--endcreditstext "CCextractor Ends crdit Testing"

**Comment by brooss** [comment]
@ccx-testerbot runtests

**Comment by wforums** [comment]
@ccx-testerbot runtests

**Comment by wforums** [comment]
@brooss After confirming with Carlos, I've added you to the list of trusted users; you can now command the bot too :+1:

**Comment by wforums** [comment]
@brooss This looks way better :+1: 

Same state as other pull requests, so that's all fine!

**Comment by brooss** [comment]
@wforums Great. Thanks for your help with this. :grin:

**Pull request merged**
