### PR TITLE
CEA-708 support improved

### PR DESCRIPTION
**Pull request by kisselef**
In this PR:
- Fixed windows build
- Multiprogram should be supported (no video samples to test though)
- Storing characters in at least 16-bit variables
- Various minor fixes

### CODE REVIEW

**Comment by kisselef** [comment]
@ccx-testerbot runtests feature-cea-708

**Comment by kisselef** [comment]
@ccx-testerbot runtests

**Comment by kisselef** [comment]
@ccx-testerbot runtests

**Comment by canihavesomecoffee** [comment]
@ccx-testerbot runtests

**Comment by canihavesomecoffee** [comment]
@ccx-testerbot runtests

**Comment by canihavesomecoffee** [comment]
@ccx-testerbot runtests

**Comment by canihavesomecoffee** [comment]
@ccx-testerbot runtests

**Comment by canihavesomecoffee** [comment]
@ccx-testerbot runtests

**Comment by kisselef** [comment]
@ccx-testerbot runtests

**Pull request merged**
