### PR TITLE
[Fix] Make -delay all output formats

### LINKED ISSUE #1103: Param "-delay" does not work in out=webvtt but works in out=srt output
(ccextractor version 0.88 from github)

Using `out=webvtt` does not add 4sec delay to text timings but `out=srt` from the same input oboyes a delay parameter fine.
```
## fail, does not add +4sec
ccextractor -codec -dvbsub -utf8 -nobom -nofc -out=webvtt \
  -in=ts "test.ts" -o "sub.vtt" \
  -delay 4000 -noteletext -nocodec teletext -datapid 0x467 -parsePAT -parsePMT
## ok, adds +4sec
ccextractor -codec -dvbsub -utf8 -nobom -nofc -out=srt \
  -in=ts "test.ts" -o "sub.srt" \
  -delay 4000 -noteletext -nocodec teletext -datapid 0x467 -parsePAT -parsePMT
```
Is it a problem here in webvtt.c file, see srt vs webvtt variable handling `ms_start,ms_end,subs_delay` values?
https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_encoders_webvtt.c#L399
https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_encoders_srt.c#L84

### PR DESCRIPTION
**Pull request by NilsIrl**
Fix #1103 

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.
- [ ] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [X] I have used CCExtractor just a couple of times.

Move up the pipeline, when the calculation of delay is done.

### CODE REVIEW

**Comment by cfsmp3** [comment]
How have you tested this? @NilsIrl 
You seem to have good ideas and know what you are doing but lack in the testing side of things :-) That's also really important, our CI system is still not perfect and the rest of us also like to be coding rather than testing...

**Comment by NilsIrl** [comment]
@cfsmp3 I've tried using with and without delay with srt, webvtt, and snupng using the file and arguments of #1166 (except -out=webvtt which changes).

Also please note that the end_time was already calculated earlier in some cases and that there were more than one encoder which didn't take into account subs_delay so this fixed more than webvtt.

**Comment by NilsIrl** [comment]
I also tested with `FX.ts` with ssa, srt and webvtt

**Comment by cfsmp3** [comment]
@canihavesomecoffee OK to merge? I can't test myself for the next 48 hours

**Comment by canihavesomecoffee** [comment]
> 
> 
> @canihavesomecoffee OK to merge? I can't test myself for the next 48 hours

Will check tomorrow

**Comment by cfsmp3** [comment]
@NilsIrl Can you solve the conflicts?

**Comment by NilsIrl** [comment]
Conflict fixed

**Comment by canihavesomecoffee** [comment]
Linux tests look OK to me, Windows is still running.

**Comment by cfsmp3** [comment]
Windows fails with error code 10 on some samples, which means NO_CAPTIONS. But it's producing that even when there's actually subtitles.

Note though that we return "no captions" for any error returned by the main loop (which sucks - the error can be anything else and we just happily convert it to no captions). 

Don't know why this would appear in Win and not linux but clearly there's something weird going on here.

@NilsIrl can you check that out, see if you can figure it out?

**Comment by NilsIrl** [comment]
> Windows fails with error code 10 on some samples, which means NO_CAPTIONS. But it's producing that even when there's actually subtitles.

Is this a regression that was introduced in this PR? Because comparing with [the results from master](https://sampleplatform.ccextractor.org/test/master/windows), I can't see a difference.

**Comment by canihavesomecoffee** [comment]
You are right @NilsIrl. I looked back a bit further, and at least since the release from 0.88 they have been returning non-expected return codes.

As such, this PR doesn't make it worse, and can be merged 👍

**Pull request merged**
