### PR TITLE
[FEATURE]Add .rpm package generation script

### PR DESCRIPTION
**Pull request by techfreakworm**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [x] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

---

Added script to generate .rpm package.
Solves a part of issue #678

### CODE REVIEW

**Comment by techfreakworm** [comment]
@rkuchumov Please check if the patch is good enough to merge. :)

**Comment by rkuchumov** [comment]
1. this script is not executable by default
2. why do you try to install package checkinstall for user? Just tell him that this package is not installed and let him install it (e.g. he'll need to `apt update` first)
3. there may be no sudo
4. why do you delete all tmp files after installation? When something fails, user would have to build everything from scratch again
5.  does these scripts fit in standard workflow of creating and distributing packages?  (I'm just lazy to google it :) )

**Comment by techfreakworm** [comment]
@rkuchumov yes it does fit in the normal work flow of creating and distributing the packages.. Except for the directories that are made.. The tree of directories used for making rpm package are generally made in `home`.. But that shouldn't be a problem I guess.. Or I can change the script to match exactly stated in official documentation of fedora or other distributions. I used instructions from the link provided by @izaron at the issues page.. 

Will commit changes related to other issues soon..  And also.. It doesn't need checkinstall package (on fedora and ubuntu), it just requires rpmbuild package.. Maybe you are talking about `debian.sh`?

**Comment by rkuchumov** [comment]
ah, damn, I've checked wrong script :)
I'll review it later again

**Comment by techfreakworm** [comment]
@rkuchumov Can you please review this and the other PR? It's 2 days left until earning of GSoC points.

**Comment by rkuchumov** [comment]
Sorry, I'm in China right now and I'll be able to check it only after May 4th

**Comment by techfreakworm** [comment]
@rkuchumov, yea sure.. No problem

**Comment by rkuchumov** [comment]
Sorry for late reply. Congrats on your acceptance to GSoC!
PR is fine and it can be merged.

**Comment by techfreakworm** [comment]
@rkuchumov Thank You. :)

**Pull request merged**
