### PR TITLE
Update VS project within up-to-date tesseract library (issue #1254)

### PR DESCRIPTION
**Pull request by apovalyaev**
- Replace "ccpan" libraries with up-to-date stuff;
- Update project additional libraries setting accordingly;
- Update build events;

### CODE REVIEW

**Comment by canihavesomecoffee** [comment]
Build shows that it is updated:

[Current master](https://github.com/CCExtractor/ccextractor/runs/620331207):
```
 Libraries used by CCExtractor
	Tesseract Version: 4.00.00alpha
	Leptonica Version: leptonica-1.74 (Dec 31 2016, 10:56:23) [MSC v.1900 LIB Release x86]
```

[This PR](https://github.com/CCExtractor/ccextractor/pull/1262/checks?check_run_id=625934618)
```
Libraries used by CCExtractor
	Tesseract Version: 4.1.1
	Leptonica Version: leptonica-1.78.0 (Apr 27 2020, 14:22:17) [MSC v.1925 LIB Debug x86]
```

@cfsmp3 If the generated binaries are usable to you, I see no reason not to merge this PR.

**Comment by cfsmp3** [comment]
@canihavesomecoffee Are you able to test some OCR program (DVB UK, I guess, such as East Enders from our sample repo?)

Looks good that it's running the right version, but is it still working? :-) Is their API 100% backwards compatible?

**Comment by apovalyaev** [comment]
> @canihavesomecoffee Are you able to test some OCR program (DVB UK, I guess, such as East Enders from our sample repo?)
> 
> Looks good that it's running the right version, but is it still working? :-) Is their API 100% backwards compatible?

Good question! @cfsmp3 , how do you usually check such kind of things (compatibility e.t.c.)?

**Comment by canihavesomecoffee** [comment]
> > @canihavesomecoffee Are you able to test some OCR program (DVB UK, I guess, such as East Enders from our sample repo?)
> > Looks good that it's running the right version, but is it still working? :-) Is their API 100% backwards compatible?
> 
> Good question! @cfsmp3 , how do you usually check such kind of things (compatibility e.t.c.)?

In most cases the Sample platform (the CI ones in the checks) should be handling it. However, not all tests are in there, and as it's not very stable at this moment, we'll have to do some manual testing...

**Comment by cfsmp3** [comment]
> > @canihavesomecoffee Are you able to test some OCR program (DVB UK, I guess, such as East Enders from our sample repo?)
> > Looks good that it's running the right version, but is it still working? :-) Is their API 100% backwards compatible?
> 
> Good question! @cfsmp3 , how do you usually check such kind of things (compatibility e.t.c.)?

Generate .srt subtitles from video files that use bitmaps, such as any of the ones here:

https://drive.google.com/drive/u/5/folders/0B_61ywKPmI0TUUk5LXJPeG1feFE

(for example, BBC East Enders)

**Comment by canihavesomecoffee** [comment]
@apovalyaev For me (using the build_ocr_hardsubx_release artifact, after adding the necessary DLL's and a eng.traineddata to the correct folder) it crashes immediately when testing it out with the east enders sample.

**Comment by apovalyaev** [comment]
> @apovalyaev For me (using the build_ocr_hardsubx_release artifact, after adding the necessary DLL's and a eng.traineddata to the correct folder) it crashes immediately when testing it out with the east enders sample.

Previous "ccpan's libraries and newly added, are all static (.lib files, not .dll). Do you mean them? Could you please point to a test scenario, you mentioned.

**Comment by canihavesomecoffee** [comment]
> > @apovalyaev For me (using the build_ocr_hardsubx_release artifact, after adding the necessary DLL's and a eng.traineddata to the correct folder) it crashes immediately when testing it out with the east enders sample.
> 
> Previous "ccpan's libraries and newly added, are all static (.lib files, not .dll). Do you mean them? Could you please point to a test scenario, you mentioned.

The used ffmpeg DLL's are not yet present in the build artifacts that are generated with the GitHub actions, so if you take the build artifact you cannot run it out of the box right now.

So my reproduction scenario is:
- Download artifact, extract to folder
- Download ffmpeg DLL's, extract to same folder
- Create a tessdata folder in that folder
- Download https://github.com/tesseract-ocr/tessdata/blob/master/eng.traineddata and place it in tessdata
- Download the BBC East Enders sample from the link Carlos posted
- Run CCExtractor on that sample

**Comment by apovalyaev** [comment]
> > > @apovalyaev For me (using the build_ocr_hardsubx_release artifact, after adding the necessary DLL's and a eng.traineddata to the correct folder) it crashes immediately when testing it out with the east enders sample.
> > 
> > 
> > Previous "ccpan's libraries and newly added, are all static (.lib files, not .dll). Do you mean them? Could you please point to a test scenario, you mentioned.
> 
> The used ffmpeg DLL's are not yet present in the build artifacts that are generated with the GitHub actions, so if you take the build artifact you cannot run it out of the box right now.
> 
> So my reproduction scenario is:
> 
> * Download artifact, extract to folder
> * Download ffmpeg DLL's, extract to same folder
> * Create a tessdata folder in that folder
> * Download https://github.com/tesseract-ocr/tessdata/blob/master/eng.traineddata and place it in tessdata
> * Download the BBC East Enders sample from the link Carlos posted
> * Run CCExtractor on that sample

For building and running, .libs and .dlls are used from windows/libs/lib/ffmpeg-lib/ folder respectively. They are copied by vs post-build actions to the project output directory. So that the application can run immediately (as it is done on CI platform, as far as I understand). 
Where are you taking ffmpeg DLL's from?

**Comment by canihavesomecoffee** [comment]
Check out the build artifacts. You'll notice they have no DLL's in them. Yes, the solution copies them to the folder, but the artifact creation action doesn't do that yet. I'm manually downloading the dll's from the folder in the repo here, which achieves the same thing as having them copied by the sln. So you can ignore that step, the others remain valid and will still cause that crash.

**Comment by apovalyaev** [comment]
> Check out the build artifacts. You'll notice they have no DLL's in them. Yes, the solution copies them to the folder, but the artifact creation action doesn't do that yet. I'm manually downloading the dll's from the folder in the repo here, which achieves the same thing as having them copied by the sln. So you can ignore that step, the others remain valid and will still cause that crash.

@canihavesomecoffee Could you please attach console output with the error you see? Thanks

**Comment by canihavesomecoffee** [comment]
> 
> 
> > Check out the build artifacts. You'll notice they have no DLL's in them. Yes, the solution copies them to the folder, but the artifact creation action doesn't do that yet. I'm manually downloading the dll's from the folder in the repo here, which achieves the same thing as having them copied by the sln. So you can ignore that step, the others remain valid and will still cause that crash.
> 
> @canihavesomecoffee Could you please attach console output with the error you see? Thanks

No output. It just starts processing output and immediately crashes. Last master build (with the old tesseract beta release) gave an assertion exception, but this one yields nothing.

You don't see anything similar when reproducing it yourself?

**Comment by apovalyaev** [comment]
> Check out the build artifacts. You'll notice they have no DLL's in them. Yes, the solution copies them to the folder, but the artifact creation action doesn't do that yet. I'm manually downloading the dll's from the folder in the repo here, which achieves the same thing as having them copied by the sln. So you can ignore that step, the others remain valid and will still cause that crash.
> 
> @canihavesomecoffee Could you please attach console output with the error you see? Thanks
> 
> No output. It just starts processing output and immediately crashes. Last master build (with the old tesseract beta release) gave an assertion exception, but this one yields nothing.
> You don't see anything similar when reproducing it yourself?

I see no crash. Is there any stable previous version which I can use to compare/check?
Also, are such kind of test-cases (video files that use bitmaps) included to CI?

**Comment by canihavesomecoffee** [comment]
So, I tried it again today:

- Version downloaded from master (https://github.com/CCExtractor/ccextractor/suites/636817977/artifacts/5261524)
- Extract zip
- Add tessdata folder, place eng.traineddata in it
- Run command
- Output: Crash without one assert printed (generic Program stopped working)
```
C:\Users\Me\Downloads\master>ccextractorwinfull.exe C:\Users\Me\Downloads\
01-BBC1.EastEnders.ts
CCExtractor 0.88, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: C:\Users\Me\Downloads\01-BBC1.EastEnders.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No][Filter profanity: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]
[Quantisation-mode: CCExtractor's internal function]

-----------------------------------------------------------------
Opening file: C:\Users\Me\Downloads\01-BBC1.EastEnders.ts
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
lstm_recognizer_->DeSerialize(tessdata_manager.swap(), &fp):Error:Assert failed:
in file C:\Users\HOME\.cppan\storage\src\42\9e\ba91\ccmain\tessedit.cpp, line 20
2

C:\Users\Me\Downloads\master>
```

- Version downloaded from your PR (https://github.com/CCExtractor/ccextractor/suites/640137581/artifacts/5338064)
- Extract zip
- Add tessdata folder, place eng.traineddata in it
- Run command
- Output: Crash without any information printed (generic Program stopped working)
```
C:\Users\Me\Downloads\branch>ccextractorwinfull.exe C:\Users\Me\Downloads\01-BBC1.EastEnders.ts
CCExtractor 0.88, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: C:\Users\Me\Downloads\01-BBC1.EastEnders.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: Auto] [Debug: No] [Buffer input: Yes]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
[Add font color data: Yes] [Add font typesetting: Yes]
[Convert case: No][Filter profanity: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]
[Quantisation-mode: CCExtractor's internal function]

-----------------------------------------------------------------
Opening file: C:\Users\Me\Downloads\01-BBC1.EastEnders.ts
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode

C:\Users\Me\Downloads\branch>
```

**Comment by apovalyaev** [comment]
> So, I tried it again today:
> 
> * Version downloaded from master (https://github.com/CCExtractor/ccextractor/suites/636817977/artifacts/5261524)
> * Extract zip
> * Add tessdata folder, place eng.traineddata in it
> * Run command
> * Output: Crash without one assert printed (generic Program stopped working)
> 
> ```
> C:\Users\Me\Downloads\master>ccextractorwinfull.exe C:\Users\Me\Downloads\
> 01-BBC1.EastEnders.ts
> CCExtractor 0.88, Carlos Fernandez Sanz, Volker Quetschke.
> Teletext portions taken from Petr Kutalek's telxcc
> --------------------------------------------------------------------------
> Input: C:\Users\Me\Downloads\01-BBC1.EastEnders.ts
> [Extract: 1] [Stream mode: Autodetect]
> [Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
> [Timing mode: Auto] [Debug: No] [Buffer input: Yes]
> [Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
> [Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
> [Add font color data: Yes] [Add font typesetting: Yes]
> [Convert case: No][Filter profanity: No] [Video-edit join: No]
> [Extraction start time: not set (from start)]
> [Extraction end time: not set (to end)]
> [Live stream: No] [Clock frequency: 90000]
> [Teletext page: Autodetect]
> [Start credits text: None]
> [Quantisation-mode: CCExtractor's internal function]
> 
> -----------------------------------------------------------------
> Opening file: C:\Users\Me\Downloads\01-BBC1.EastEnders.ts
> File seems to be a transport stream, enabling TS mode
> Analyzing data in general mode
> lstm_recognizer_->DeSerialize(tessdata_manager.swap(), &fp):Error:Assert failed:
> in file C:\Users\HOME\.cppan\storage\src\42\9e\ba91\ccmain\tessedit.cpp, line 20
> 2
> 
> C:\Users\Me\Downloads\master>
> ```
> 
> * Version downloaded from your PR (https://github.com/CCExtractor/ccextractor/suites/640137581/artifacts/5338064)
> * Extract zip
> * Add tessdata folder, place eng.traineddata in it
> * Run command
> * Output: Crash without any information printed (generic Program stopped working)
> 
> ```
> C:\Users\Me\Downloads\branch>ccextractorwinfull.exe C:\Users\Me\Downloads\01-BBC1.EastEnders.ts
> CCExtractor 0.88, Carlos Fernandez Sanz, Volker Quetschke.
> Teletext portions taken from Petr Kutalek's telxcc
> --------------------------------------------------------------------------
> Input: C:\Users\Me\Downloads\01-BBC1.EastEnders.ts
> [Extract: 1] [Stream mode: Autodetect]
> [Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
> [Timing mode: Auto] [Debug: No] [Buffer input: Yes]
> [Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
> [Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
> [Add font color data: Yes] [Add font typesetting: Yes]
> [Convert case: No][Filter profanity: No] [Video-edit join: No]
> [Extraction start time: not set (from start)]
> [Extraction end time: not set (to end)]
> [Live stream: No] [Clock frequency: 90000]
> [Teletext page: Autodetect]
> [Start credits text: None]
> [Quantisation-mode: CCExtractor's internal function]
> 
> -----------------------------------------------------------------
> Opening file: C:\Users\Me\Downloads\01-BBC1.EastEnders.ts
> File seems to be a transport stream, enabling TS mode
> Analyzing data in general mode
> 
> C:\Users\Me\Downloads\branch>
> ```

Thank you, @canihavesomecoffee. I've run a lot of times and can also observe that the output result might differ from time to time. 
It is written that all the libraries being shipped through VKPG have been verified to work fine within VS2015,17 and 19. It gives a reason that start thinking that there is some bug/issue in the code (some kind of not-properly initialized data or something like that) which has been here previously also. But it starts explicitly showing itself only now. THat is wh I asked you about some previously stable-version-results.
May be @cfsmp3 can add something.

**Comment by apovalyaev** [comment]
Just tried the following: takes all the includes/libraries right from vcpkg repository (through vcpkg integrate), the same result - something wrong within initialization/some other errors.

**Comment by cfsmp3** [comment]
Closing, since it seems abandoned.

**Pull request closed without merging**
