### PR TITLE
[FIX] Fix failing tests (WIP)

### PR DESCRIPTION
**Pull request by NilsIrl**
**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [X] I have used CCExtractor just a couple of times.

---

### CODE REVIEW

**Comment by NilsIrl** [comment]
OMG!!!!!!!!!!!!!!

**Comment by canihavesomecoffee** [comment]
@NilsIrl Looks like it's fixed now... At least on Linux.

**Comment by cfsmp3** [comment]
I'm terrified at the idea of replacing enums with unsigned char - what's the rationale for this?

**Comment by NilsIrl** [comment]
This is terribly confusing.

84ba7c5238db40abd5535842861e688c274bd219 failed many tests but 84ba7c5238db40abd5535842861e688c274bd219 gets the same result as this PR.

What I don't understand is that no C code has been changed in the meanwhile so why did  84ba7c5238db40abd5535842861e688c274bd219 fail so many tests

**Comment by NilsIrl** [comment]
> I'm terrified at the idea of replacing enums with unsigned char - what's the rationale for this?

It was already like that before #1154

**Pull request closed without merging**
