### PR TITLE
Fix for * to @ issue based on packet address.

### PR DESCRIPTION
**Pull request by abhishek-vinjamoori**
Possible fix. Must do more testing for * , @ and § samples

### CODE REVIEW

**Comment by abhishek-vinjamoori** [comment]
Text is over-written

**Comment by abhishek-vinjamoori** [comment]
Possible fix for #249. 
Regression testing required, as data is over-written in special cases.

**Comment by canihavesomecoffee** [comment]
@ccx-testerbot runtests master

**Comment by canihavesomecoffee** [comment]
Looks good :+1:

**Comment by canihavesomecoffee** [comment]
@ccx-testerbot runtests master

**Comment by cfsmp3** [comment]
Merged a different solution but this one is valid - you get points.
Please mention the PR number in your proposal.

**Pull request closed without merging**
