### PR TITLE
[IMPROVEMENT] Removed unused import in *.py files

### PR DESCRIPTION
**Pull request by kartik-25**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [x] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

---

Removes all the unused imports in *.py files

### CODE REVIEW

**Comment by TheFaR8** [comment]
Have you tried it?

**Comment by kartik-25** [comment]
Yes @TheFaR8

**Comment by kartik-25** [comment]
@cfsmp3 have a look at this PR.

**Comment by kartik-25** [comment]
@canihavesomecoffee please have a look.

**Comment by cfsmp3** [comment]
We probably don't want to remove those imports even if they are not being used at this time - after all, it's the "canonical" way to import ccextractor into python.

**Pull request closed without merging**
