### PR TITLE
[IMPROVEMENT] Update Rust and fix windows build

### PR DESCRIPTION
**Pull request by prateekmedia**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.
- [ ] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [x] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

---

- Update Rust to stable (done)
- Switch to `rusty_ffmpeg` and `rsmpeg` from `ffmpeg-sys-next`
- Fix windows CI (add support of vcpkg for static linking and supporting both architectures)

### CODE REVIEW

**Comment by prateekmedia** [comment]
The test results doesn't look good, 0 passed out of them.

**Comment by cfsmp3** [comment]
> The test results doesn't look good, 0 passed out of them.

I suspect the CI, but @canihavesomecoffee will have to confirm what's going on :-)

**Comment by prateekmedia** [comment]
I checked the ccextractorwinfull.exe and It couldn't find the eng.traineddata filed for hardsubx, I see that vcpkg doesn't include that by default so we would have to copy that in the PostBuildScript of vccxproj. But the problem is that I am not sure if It will be able to find the eng.traineddata path even after bundling it in the script at some location.

**Comment by cfsmp3** [comment]
> I checked the ccextractorwinfull.exe and It couldn't find the eng.traineddata file for hardsubx, I see that vcpkg doesn't include that by default so we would have to copy that in the PostBuildScript of vccxproj. But the problem is that I am not sure if It will be able to find the eng.traineddata path even after bundling it in the exe at some location.

We should be able to just wget it from the github action itself  ( https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata )

And then use it.

**Pull request merged**
