### PR TITLE
[FEATURE] Added support for encoding into an MCC File. (CCExtractor#733)

### PR DESCRIPTION
**Pull request by robdt**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [X] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

---

{pull request content here}

### CODE REVIEW

**Comment by canihavesomecoffee** [comment]
Hi @robdt,

Can you take a look at these errors for the Windows build environment?

```
"ccextractor\windows\ccextractor.sln" (default target) (1) ->
"ccextractor\windows\ccextractor.vcxproj" (default target) (2) ->
(Link target) ->
  mp4.obj : error LNK2019: unresolved external symbol _mcc_encode_cc_data referenced in function _process_clcp [ccextractor\windows\ccextractor.vcxproj]
  ccx_decoders_common.obj : error LNK2001: unresolved external symbol _mcc_encode_cc_data [ccextractor\windows\ccextractor.vcxproj]
  Debug\ccextractorwin.exe : fatal error LNK1120: 1 unresolved externals [ccextractor\windows\ccextractor.vcxproj]
 
    1188 Warning(s)
    3 Error(s)
```

Looks like the file should be just added to the .sln :+1:

**Comment by robdt** [comment]
Hey @canihavesomecoffee,

Thanks! It looked like it should be added into the Visual C Project file, so I added it there. There weren't any other files in the .sln like there were in the .vcxproj. I am hoping that is correct. I am still looking at why there are issues with the tests. I think it is related to the command line option I added. Please let me know if you see that it didn't fix the problem with Windows. I am still a little handicapped there as I don't have access to a Windows box or Visual Studio to build and test.

**Comment by canihavesomecoffee** [comment]
Hi @robdt,

Thanks for the changes! We're down to one issue now: the mcc file requires `uuid/uuid.h`, which is not available on Windows.

As this library is not natively available (afaik) for Windows, we might have to look into a solution as mentioned here: https://github.com/djp952/prebuilt-libuuid/issues/1#issuecomment-427341280

@cfsmp3 What would you prefer to do?

**Comment by cfsmp3** [comment]
The less dependencies the better - if we can copy/paste the code for those functions from a well tested source I'd do that, unless there's a good reason not to.

**Comment by robdt** [comment]
@canihavesomecoffee - That would be easy to pull in. In fact I could make that the code for all platforms if that made more sense than leaving Linux and Mac as they are. Let me know if you want me to proceed down that path.

**Comment by cfsmp3** [comment]
@robdt  yes please do that - let's use that code for all platforms so we can avoid the dependency. I find it helps a lot with portability (and building, in general).

**Comment by robdt** [comment]
Thanks @cfsmp3, will do!

**Comment by robdt** [comment]
@canihavesomecoffee @cfsmp3 - I had been redirected, but I am now able to get back to this.

I was re-looking at everything, and I am not sure why I thought that I could leverage the code described in https://github.com/djp952/prebuilt-libuuid/issues/1#issuecomment-427341280 for anything beyond windows. It is clearly based on the windows call `CoCreateGuid()`. Anyway, it still has the requisite functionality for Windows, so my plan was to:
1) Pull the two files from that project into src/lib_ccx as two new files. Maybe win_uuid.cpp/win_uuid.h
2) Leverage preprocessor directives (specifically `_WIN32`) to include the header and function for windows builds
3) Add the new files to the windows build, but not necessarily the others as the current implementation will work for Mac and Linux

This stops me at some of the CMake stuff. The files I am leveraging are C++ files. Is it possible to port that file with the .cpp extension and the build system is smart enough to get it compiled? Or do I have to do something special to get this integrated. Sorry, windows dev isn't my thing so I am not super literate around it.

**Comment by cfsmp3** [comment]
@canihavesomecoffee can you check why the build fails and fix if you can? (I'm unable to build on Windows these days). Feel free to merge when you're happy.

**Comment by canihavesomecoffee** [comment]
Hi @robdt, the PR looks fine. I'll try and build it tomorrow (and see why the CI isn't building), could you take a look at the results from Travis? It seems that for Mac, in 2 tests it's including the windows_uuid.c/h files, which obviously cause errors :)

https://travis-ci.org/CCExtractor/ccextractor/jobs/568105966#L3148

If you could do that (and I check the build on Windows tomorrow), I think this PR will be able to be merged :1st_place_medal:

**Comment by robdt** [comment]
Hey @canihavesomecoffee, sorry about that. Small oversight, fixed now. Please let me know if there is anything else you need from me or that I can do for this.

**Comment by canihavesomecoffee** [comment]
Hi @robdt, if you want to help out, the Windows compilation is failing with this as error:
```
c:\users\bot\documents\ci\ccextractor\src\lib_ccx\win_uuid.h(40): error C2143: syntax error: missing ')' before '&' [C:\User
s\bot\Documents\ci\ccextractor\windows\ccextractor.vcxproj]
c:\users\bot\documents\ci\ccextractor\src\lib_ccx\win_uuid.h(40): error C2143: syntax error: missing '{' before '&' [C:\User
s\bot\Documents\ci\ccextractor\windows\ccextractor.vcxproj]
c:\users\bot\documents\ci\ccextractor\src\lib_ccx\win_uuid.h(40): error C2059: syntax error: '&' [C:\Users\bot\Documents\ci\
ccextractor\windows\ccextractor.vcxproj]
c:\users\bot\documents\ci\ccextractor\src\lib_ccx\win_uuid.h(40): error C2059: syntax error: ')' [C:\Users\bot\Documents\ci\
ccextractor\windows\ccextractor.vcxproj]
c:\users\bot\documents\ci\ccextractor\src\lib_ccx\win_uuid.h(45): error C2143: syntax error: missing ')' before '&' [C:\User
s\bot\Documents\ci\ccextractor\windows\ccextractor.vcxproj]
c:\users\bot\documents\ci\ccextractor\src\lib_ccx\win_uuid.h(45): error C2143: syntax error: missing '{' before '&' [C:\User
s\bot\Documents\ci\ccextractor\windows\ccextractor.vcxproj]
c:\users\bot\documents\ci\ccextractor\src\lib_ccx\win_uuid.h(45): error C2059: syntax error: '&' [C:\Users\bot\Documents\ci\
ccextractor\windows\ccextractor.vcxproj]
c:\users\bot\documents\ci\ccextractor\src\lib_ccx\win_uuid.h(45): error C2059: syntax error: ')' [C:\Users\bot\Documents\ci\
ccextractor\windows\ccextractor.vcxproj]
```

I tried out some things, but I can't seem to fix it right now :(

**Comment by robdt** [comment]
Hey @canihavesomecoffee I think it is a C++ vs. C problem and your C complier doesn't like the pass by reference when it looks at that header. I am going to rewrite it in a C compliant pointer way. Will check that in in a few mins.

**Comment by robdt** [comment]
Dug closer into what the uuid_t is. Apparently it is an array, so it was already passing a pointer.

Just a thought, if this doesn't work, the MCC spec says that you need to add a UUID in the text there. It doesn't specifically say that it needs to be valid, or unique. ;-)

**Comment by cfsmp3** [comment]
> Dug closer into what the uuid_t is. Apparently it is an array, so it was already passing a pointer.
> 
> Just a thought, if this doesn't work, the MCC spec says that you need to add a UUID in the text there. It doesn't specifically say that it needs to be valid, or unique. ;-)

I see uuid_t being used but not defined anywhere.

Anyway really this should be the same code for all platforms. Why use an internal definition for Windows (that uses Windows specific stuff) and depend on an external thing for linux and Mac? Just have the same code for all platforms. It will make testing much easier for you.

I'd say if you are calling it a uuid then it should be a uuid. At least valid. Unique, since that's hard to generally really well, probably not, but at least use a timestamp so it's different between runs of CCExtractor, even if there's a bigger than desired chance of collision between separately generated uuid's.  rand() is also portable so it should help.

Whatever you do, please don't hardcode a value or anything like that :-)

**Comment by robdt** [comment]
libuuid is part of the linux kernel (util-linux-ng package) and I assume the mac version is a darwin port (I didn't even need a -l to add the library on Mac). Windows seems to have gone their own direction by including that functionality as part of their StdAfx. The APIs looked almost identical, but frustratingly different enough that it wasn't just a simple header swap. Everything seems to be using the uuid_t type (the libuuid stuff on linux/mac for sure, but it also looks like that same type, which is just a collection of bytes, is also used on Windows).

I am hoping that last pass has it fixed. There is no C++ in the header, windows is segregated by WIN32 compiler directive, and the stdafx call looked to be compliant with the spec. Fingers crossed that it compiles now. I unfortunately still don't have access to Windows box to compile and test.

**Comment by cfsmp3** [comment]
> I unfortunately still don't have access to Windows box to compile and test.

Precisely. Remove all that code that is separate between platforms and replace with portable code that you can test in yours. We really don't want to have directives to switch between platforms in anything that is not absolutely necessary. Generating a random string or number definitely doesn't fall in this category.

While we test in Windows, Linux and Mac (this one just from time to time, whenever a Mac user feels like reporting issues and helping one) we aim to be portable and work on FreeBSD or anything else that has a C compiler. Having separate branches make things much harder, and should be unneeded in a program like this.

**Comment by robdt** [comment]
I would have to look deeper at the uuid spec to be certain, but I was under the impression that there were a hand full of different versions of UUID which use the system time, mac address of the host, hashing of an identifier, etc. to build them. But I think there is one version which uses a true random number as its base. Do you want me to pull out use of the library and replace it with an implementation of the uuid from spec? (specifically version 4, that true random one) If so, that would be fine, but it might be a little bit before I have that complete. I got redirected this week and would have to circle back before I could get it coded.

**Comment by cfsmp3** [comment]
Yes, I think that's the way to go.

**Comment by robdt** [comment]
Sounds good! I should be able to circle back and get it implemented in a bit

**Comment by robdt** [comment]
I was able to switch out the uuid lib with a spec compliant implementation. I also got it squished back down so that we didn't have the entire saga of the uuid in the pull request. Please let me know if there is anything more that you need from my end.

**Comment by canihavesomecoffee** [comment]
It's currently not building on the CI linux environment:

`../src/lib_ccx/ccx_encoders_mcc.c: In function ‘generate_mcc_header’:
../src/lib_ccx/ccx_encoders_mcc.c:100:5: error: unknown type name ‘uuid_t’
     uuid_t binuuid;`

**Comment by thealphadollar** [comment]
@canihavesomecoffee @cfsmp3 Should we merge this?

**Pull request merged**
