### PR TITLE
[IMPROVEMENT] Remove freep warning

### PR DESCRIPTION
**Pull request by NilsIrl**
**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [X] I have used CCExtractor just a couple of times.

---

Change `freep` into a macro to remove all the warnings it generated.

### CODE REVIEW

**Comment by cfsmp3** [comment]
Hold on, this must be completely breaking things - if you don't pass a pointer to the pointer you want to free then you can't change the pointer value from inside freep() which is the whole point of it in the first place!
```
char *hello = (char *) malloc (10)
freep (&hello);
assert (hello == NULL);
```

That's going to fail if you pass "hello" instead of "&hello", because freep() won't be able to change the value of the outside variable.

**Comment by NilsIrl** [comment]
Or we could pass a `void *` to `freep` and then cast in there.

**Comment by cfsmp3** [comment]
I've merged your stuff. I don't want to cast to void * in 30 places.

**Comment by NilsIrl** [comment]
> I don't want to cast to void * in 30 places.

187 to be exact :joy:

**Pull request merged**
