### PR TITLE
Case fix teletext

### PR DESCRIPTION
**Pull request by mailumangjain**
Case fix for TeleText. #139
Base Sample /John(lowercase)

### CODE REVIEW

**Comment by wforums** [comment]
I'll run the test suite tomorrow for this, and I'll keep you up 2 date :+1:

**Comment by mailumangjain** [comment]
okay.

**Comment by wforums** [comment]
@ccx-testerbot runtests

**Comment by wforums** [comment]
Looks quite good, except for 17, 20 & 21... Looks like the end of the line with an I is cut off and either vanishes or is appended to the next line. See: http://ccextractor.canihavesome.coffee/reports/43/Report__Teletext_2015-08-14_131154.html

**Comment by mailumangjain** [comment]
ok I think I need to handle " I\n" string. I have not included this is in my logic. Will update PR.

**Comment by mailumangjain** [comment]
@wforums can you email/share file no. 17,20,21 of your teletext test files ?

**Comment by wforums** [comment]
Hey, they are available for download here:

http://gsocdev.ccextractor.org/~willem/teletext/17.mpg (801mb)
http://gsocdev.ccextractor.org/~willem/teletext/20.mpg (827mb)
http://gsocdev.ccextractor.org/~willem/teletext/21.mpg (880mb)

**Pull request closed without merging**
