### PR TITLE
Add flag for Page Segmentation Modes control

### PR DESCRIPTION
**Pull request by Neo2SHYAlien**
**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.
- [X] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [X] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

---

I added an flag `-psm` for controlling PSM ([Page Segmentation Modes](https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html#page-segmentation-method)) in Tesseract. The default option (3) gives me quite bad results. When I use 6, 11, or 12 for Bulgarian, it gives me much better OCR results. I haven't tested other languages yet, but I expect improvements as well if other mode is used.

p.s This PR is continue #1544 which was closed after the rebase 🥲

### CODE REVIEW

**Comment by Neo2SHYAlien** [comment]
@cfsmp3 After the resync of the main branch previous PR #1544 was closed automatically.  I hope the code change to be good enough I'm nod a daily dev 😊

**Comment by PunitLodha** [comment]
@prateekmedia have you added this flag already?

**Comment by PunitLodha** [comment]
@prateekmedia could you add it to this PR itself?

**Comment by prateekmedia** [comment]
@PunitLodha Here I have made a PR to his repo:
https://github.com/Neo2SHYAlien/ccextractor/pull/1

**Comment by Neo2SHYAlien** [comment]
@prateekmedia merged

**Review by prateekmedia — APPROVED** [review]
Logic looks good although not tested myself!

**Comment by PunitLodha** [comment]
@prateekmedia the tests aren't passing yet

**Comment by prateekmedia** [comment]
@PunitLodha This PR needs rebase again.

**Pull request merged**
