### PR TITLE
[IMPROVEMENT] GPAC changes from hori branch

### PR DESCRIPTION
**Pull request by gray-v**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [X] I have used CCExtractor just a couple of times.

---

https://github.com/CCExtractor/ccextractor/pull/838 was closed without being resolved so I copied that and I'm going to work on it to fix the bugs preventing it from being merged.

WIP

### CODE REVIEW

**Comment by Hori75** [comment]
There is maths.h instead of math.h, have you seen it?

**Comment by gray-v** [comment]
Yah I merged maths.h into math.h since they were the same except renamed and math is the proper name

**Comment by Hori75** [comment]
Are you sure to add alloc.c? I think that's not needed, I closed my PR because cannot find out why CCExtractor working without alloc.c in gpacmp4.

**Comment by gray-v** [comment]
Closed since #838 was reopened.

**Pull request closed without merging**
