### PR TITLE
Split to sentences implementation

### PR DESCRIPTION
**Pull request by maxkoryukov**
Split incoming subs to separated sentences, with duplicate-detection.

Replacement for PR #491

Usage:
```shell
./ccextractor -sbs ~/source.ts
```

Currently, it works only with `sub->type == CC_BITMAP`. Implementation details - in comments to the PR.

The PR contains tests, a concise description attached (`test/README.md`) 

#### New output

```
1
00:00:00,001 --> 00:00:00,189
Oleon costs.

2
00:00:00,191 --> 00:00:00,783
buried in the annex, 95 Oleon costs.

3
00:00:00,785 --> 00:00:05,159
Didn't want to acknowledge the pressures on hospitals, schools and infrastructure.
```

#### Old output

```
1
00:00:00,001 --> 00:00:00,000
Oleon

2
00:00:00,001 --> 00:00:00,189
Oleon costs.

3
00:00:00,190 --> 00:00:00,889
buried in the annex, 95 Oleon costs.
Didn't

4
00:00:00,890 --> 00:00:01,129
buried in the annex, 95 Oleon costs.
Didn't want

5
00:00:01,130 --> 00:00:01,359
buried in the annex, 95 Oleon costs.
Didn't want to

6
00:00:01,360 --> 00:00:02,059
buried in the annex, 95 Oleon costs.
Didn't want to acknowledge

7
00:00:02,060 --> 00:00:02,299
buried in the annex, 95 Oleon costs.
Didn't want to acknowledge the

8
00:00:02,300 --> 00:00:03,419
Didn't want to acknowledge the
pressures

9
00:00:03,420 --> 00:00:03,609
Didn't want to acknowledge the
pressures on

10
00:00:03,610 --> 00:00:04,029
Didn't want to acknowledge the
pressures on hospitals,

11
00:00:04,030 --> 00:00:04,779
Didn't want to acknowledge the
pressures on hospitals, schools

12
00:00:04,780 --> 00:00:05,019
Didn't want to acknowledge the
pressures on hospitals, schools and

13
00:00:05,020 --> 00:00:05,159
pressures on hospitals, schools and
infrastructure.

```

### CODE REVIEW

**Comment by cfsmp3** [comment]
Please test with all the files here (the UK ones):

http://www.ccextractor.org/doku.php?id=public:general:tvsamples

Does it work OK with and without -sbs? Without it output should be the same for all files, with it it should be the same for channels that don't do real time transcribing and corrected for those that do (Sky News, BBC News).

**Comment by maxkoryukov** [comment]
@cfsmp3 are there any tool, which could help to run `ccextractor` several times for a bunch of files, and compare output (to be clear: not _compare_, but _check correctness_) ???

**Comment by cfsmp3** [comment]
Nah, check correctness no :-) We have a "check with last result that was
OK" tool, but it's not really the same thing, since things may have
improved. So this tool will tell your if your PR made things worse, not
better.

**Comment by maxkoryukov** [comment]
@cfsmp3 for the most cases it is enough, when tests just tell, that the code is not degraded))

**Comment by cfsmp3** [comment]
@canihavesomecoffee is the right person to ask for access to the regression system.

**Pull request merged**
