### PR TITLE
[FEATURE] Add WebVTT output from Matroska (Issue #724)

### PR DESCRIPTION
**Pull request by LucasYoung**
**In raising this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows:**

- [ ] I have never used CCExtractor.
- [X] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

---
This pull request implements extraction of WebVTT subtitles from Matroska files. I am hoping to earn 5 GSOC qualification points from this pull request.

I have tested this code with the sample video in issue #724 and the output appears to be correct. However, I have not been able to find other applicable test cases for this code (mkv files with WebVTT subtitles). Also, all of my testing was done on a 64-bit Windows machine.

### CODE REVIEW

**Comment by Izaron** [comment]
Looks adequate, thanks! But why you need skip four bytes` exactly?
Also don't edit vcxproj files, they should be unchanged in git.

**Comment by LucasYoung** [comment]
The text of each BlockAddition started at the fifth byte. I'm not sure what information the first four bytes represent. They could be header information, but I couldn't find specifications on the structure of a BlockAddition.

**Comment by Izaron** [comment]
Look at this: https://www.matroska.org/technical/specs/index.html
After Block Additions appears, we will get in deeper level BlockMore elements (multiple) indicated by byte A6, and in even deeper level BlockAdditional indicated by A5 what we can read without skipping. I guess, in sample file you just got these 4 bytes in each case: A6,A5,??,??.

**Comment by cfsmp3** [comment]
Merged, points awarded.

**Pull request merged**
