### PR TITLE
[FEATURE] Simple MacOS GUI

### PR DESCRIPTION
**Pull request by sampoder**
- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [x] I have used CCExtractor just a couple of times.

---

I have created a simple GUI for MacOS. It was generated using the open-source Platypus tool created by Sveinbjörn Þórðarson after I saw a blog post about it and felt it would help CCExtractor. 

The reason I feel that this feature should be added is because the command line can be complex for some people. A simple GUI like this is perfect for these people as all they have to do it drag in a file. However, for more advanced users, they can still use the command line. I have tried to make the install process as simple as possible

Maybe if there is interest in a more advanced GUI I can try and custom develop one.

### CODE REVIEW

**Comment by canihavesomecoffee** [comment]
@cfsmp3 Any thoughts?

@MatejMecka Can you check this?

**Comment by cfsmp3** [comment]
I don't have a Mac handy - @MatejMecka  ?

**Comment by MatejMecka** [comment]
Working on it! :)

**Comment by MatejMecka** [comment]
Currently the Implementation is Simple as the GUI states but There should be a helpful log or maybe a loading indicator or alert when CCExtractor finishes. I got lost for a second being unsure if it worked or not, since previously I had not set up ccextractor at /usr/local/ and when i dumped the video button i didn't notice anything happening

**Comment by sampoder** [comment]
I'm not not able to Google Code In anymore this year for personal reasons :( but I'll have a go fixing this

**Comment by canihavesomecoffee** [comment]
> 
> 
> I'm not able to Google Code In anymore this year for personal reasons :( but I'll have a go fixing this

That'd be great :+1:

**Comment by sampoder** [comment]
I added an alert when the process is complete

**Comment by cfsmp3** [comment]
@sampoder what's the current status of this? Maybe we should close this PR until you're ready to come back?

**Comment by sampoder** [comment]
@cfsmp3 I made the requested changes in the two most recent commits

**Comment by cfsmp3** [comment]
Merged but @MatejMecka feel free to test more and comment :-)

**Comment by NilsIrl** [comment]
Is it normal that so many binary files are included?

**Comment by MatejMecka** [comment]
Those are standard MacOS files :)

**Pull request merged**
