### PR TITLE
**[FIX]** Fixed folder path bug when compiling with ENABLE_HARDSUBX=yes

### PR DESCRIPTION
**Pull request by mmomasters**
The folder is missing for the capi.h include so I added it.
OLD : #include "capi.h"
NEW : #include "tesseract/capi.h"

Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.
- [  ] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [X] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

---

{pull request content here}

### CODE REVIEW

**Comment by thealphadollar** [comment]
@cfsmp3 Can we close / update this?

**Comment by cfsmp3** [comment]
@thealphadollar it conflicts so I can't merge. But I think this is one of those patches that don' well on Windows and linux at the same time. @canihavesomecoffee are you able to test?

**Comment by thealphadollar** [comment]
@canihavesomecoffee ping.

**Comment by canihavesomecoffee** [comment]
This was fixed through merging #1105 in the meanwhile.

Nevertheless, @mmomasters, thank you for taking the time and effort to try and fix! 🥇

**Pull request closed without merging**
