### PR TITLE
[FIX] Move files into appropriate directories & fix build scripts.

### PR DESCRIPTION
**Pull request by saurabhshri**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [x] I am an active contributor to CCExtractor.

---

The wrappers and extractors used to create API are deeply integrated with source code and keeping them outside source directory was creating all sorts of build problems and code inconsistency.
This PR moves those folders at proper place and (hopefully) fix all the build scripts.

The thing to note is that I am totally unsure how it will affect the python module (though I have changed the path at all places I could find) and I am hoping @Diptanshu8 will soon have look at it and send appropriate PR.

### CODE REVIEW

**Comment by saurabhshri** [comment]
Build tested on macOS (CMake, build scripts), Linux (CMake, build, builddebug).

@techfreakworm Please test autoconf scripts, and update if necessary. You may send a PR directly to https://github.com/saurabhshri/ccextractor/tree/api_fixes and I'll merge it and this PR will automatically be updated with your commits. Just make sure to send them on "api_fixes" branch.

**Comment by techfreakworm** [comment]
OK sure, I'll check the autoconf scripts. And send a PR tomorrow.

**Comment by saurabhshri** [comment]
@techfreakworm At least autoconf script builds successfully in Linux (Sample-Platform).

**Comment by techfreakworm** [comment]
@saurabhshri I checked, I guess you already did the necessary work in `Makefile.am`, the program compiles fine with Autotools.

**Comment by saurabhshri** [comment]
Windows build is successful as well. Refactoring is complete. Python module probably needs to be updated, but that will be in a separate PR.

**Comment by saurabhshri** [comment]
Fixes #774 #776 !

**Pull request merged**
