### PR TITLE
Add CI and docs for rust lib

### PR DESCRIPTION
**Pull request by PunitLodha**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.
- [ ] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [x] I am an active contributor to CCExtractor.

---
Add build and format CI for rust code
Add docs on how to compile rust code

Merge only after #1351 is merged

### CODE REVIEW

**Comment by canihavesomecoffee** [comment]
What about Windows? Is it possible to add a workflow for building on Windows with Rust too?

**Comment by PunitLodha** [comment]
I am facing some issues due to clang/llvm missing on windows. I'll try to fix it

**Comment by canihavesomecoffee** [comment]
> I am facing some issues due to clang/llvm missing on windows. I'll try to fix it

Full code checking isn't needed (unless Rust of course has a dependency on clang/llvm), building the executable is what matters most :)

See what you can do, it's not mandatory for this PR to be mergeable (can be in a later one)

**Comment by PunitLodha** [comment]
Clang is required for rust-bindgen to generate bindings for C code. I did figure that out, but now i get this error:- 

`  ./../lib_ccx/ccx_encoders_common.h:5:11: fatal error: '..\\win_iconv\\iconv.h' file not found, err: true`
https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_encoders_common.h#L4-L5

win_iconv is located in thirdparty folder, So shouldn't the path here be ..\\\thirdparty\\\win_iconv\\\iconv.h?

**Comment by cfsmp3** [comment]
> win_iconv is located in thirdparty folder, So shouldn't the path here be ..\\thirdparty\\win_iconv\\iconv.h?

Possibly? Seems strange that the SP hasn't picked that error, though, but if it fixes for you by all means change it.

**Comment by canihavesomecoffee** [comment]
> > win_iconv is located in thirdparty folder, So shouldn't the path here be ..\thirdparty\win_iconv\iconv.h?
> 
> Possibly? Seems strange that the SP hasn't picked that error, though, but if it fixes for you by all means change it.

Note that the cmake build on Windows has been failing for a while (see #1352)... It's not a hard requirement to complete a test run, because the "regular" manner to build the executables (through the VS project) works ok.

So that cmake build error might be hiding the issue Punit is encountering here.

**Comment by PunitLodha** [comment]
> Possibly? Seems strange that the SP hasn't picked that error, though, but if it fixes for you by all means change it.

Changing the path does fix that issue. So I think I should make a different PR for that fix? 
Also, now I have run into another issue, 
```
 ./../lib_ccx/stdintmsc.h:69:27: error: typedef redefinition with different types ('char' vs 'signed char'), err: true
  ./../lib_ccx/stdintmsc.h:90:19: error: typedef redefinition with different types ('int16_t' (aka 'short') vs 'int'), err: true
  ./../lib_ccx/stdintmsc.h:94:19: error: typedef redefinition with different types ('uint16_t' (aka 'unsigned short') vs 'unsigned int'), err: true
```

stdintmsc.h does mention that it must be used only with Microsoft Visual C++ compilers. I have set a regex to only generate bindings for types with `_dtvcc_` in their name. I don't know why bindgen is trying to generate bindings for that header file

**Comment by cfsmp3** [comment]
> Changing the path does fix that issue. So I think I should make a different PR for that fix?

Yes, please.

>  ./../lib_ccx/stdintmsc.h:69:27: error: typedef redefinition with different types ('char' vs 'signed char'), err: true
>   ./../lib_ccx/stdintmsc.h:90:19: error: typedef redefinition with different types ('int16_t' (aka 'short') vs 'int'), err: true
>   ./../lib_ccx/stdintmsc.h:94:19: error: typedef redefinition with different types ('uint16_t' (aka 'unsigned short') vs 'unsigned int'), err: true

Those are equivalent I think - at least in the architectures we care about. So it's a matter of tracking the difference down (where is the other definition?) and adjusting one of them.

There's some value in bindgen and/or rust giving us a hard time for our inconsistencies :-)

**Comment by PunitLodha** [comment]
https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_common_platform.h#L56-L61
Both the #includes here do the same thing
disable_warnings.h -> https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/disable_warnings.h
So we should remove one

Clang also defines _MSC_VER, but we want to include <stdintmsc.h> only on Microsoft Visual C++ compilers, so we need to change this, https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_common_platform.h#L58, to `#if defined(_MSC_VER) && !defined(__clang__)`

**Pull request merged**
