### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by NilsIrl**
**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [X] I have used CCExtractor just a couple of times.

---

Addresses https://github.com/CCExtractor/ccextractor/pull/402#discussion_r368041348

### CODE REVIEW

**Comment by cfsmp3** [comment]
Is this a theoretical fix or actually tested? :-)

**Comment by NilsIrl** [comment]
> Is this a theoretical fix or actually tested? :-)

Tested with `telecine.ts` and `01-BBC1.EastEnders.ts`.

**Comment by jakubvojacek** [comment]
> > Is this a theoretical fix or actually tested? :-)
> 
> Tested with `telecine.ts` and `01-BBC1.EastEnders.ts`.

Hello

this is unrelated to the reported issue with never disappearing dvb subs, right?

Thank you
Jakub

**Comment by NilsIrl** [comment]
> this is unrelated to the reported issue with never disappearing dvb subs, right?

If you could link the issue

**Comment by cfsmp3** [comment]
> If you could link the issue

https://github.com/CCExtractor/ccextractor/issues/1104

Jakub is a major CCExtractor user, so if you are looking for a bug to fix right now that's a good candidate.

**Pull request merged**
