### PR TITLE
[IMPROVEMENT] Test with OCR and HARDSUBX

### PR DESCRIPTION
**Pull request by NilsIrl**
**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [X] I have used CCExtractor just a couple of times.

---

@canihavesomecoffee

### CODE REVIEW

**Comment by canihavesomecoffee** [comment]
I'd rather see separate build sections/jobs for that.

**Comment by NilsIrl** [comment]
as in a different file?

**Comment by canihavesomecoffee** [comment]
No, as in a separate step (like we have now for build_shell, build_autoconfigure, build_cmake).

**Comment by NilsIrl** [comment]
done

**Pull request merged**
