### PR TITLE
return a non-zero return code if no subtitles were found

### PR DESCRIPTION
**Pull request by anukul**
WIP
i'm making this pull request right now to discuss what would be the best way to go about the changes.

### CODE REVIEW

**Comment by anukul** [comment]
No modifications have been made (yet) for raw mode since I could not find any suitable input files to test it.
From the discussion on [codein.withgoogle.com](https://codein.withgoogle.com/dashboard/task-instances/6204931570663424/), I was told to generate a raw input file from ccextractor itself.

However, this method did not work as ccextractor failed to produce the subtitles from a raw output file generated by the program itself.

The .raw output file seems unusually small in size and contains very little useful data.

	ÿÿÿÿï»¿<subpictures>
	<stream>
	
	</stream>
	</subpictures>

Another bug I noticed was that `out=bin` does not create a meaningful subtitle file for mp4 input.

**Comment by cfsmp3** [comment]
.mp4 is a very special case - it's not processed using the regular flow. Try a .ts if you want to produce .bin or .raw files. Both files contain only the CC data, so they're always going to be really small (a few KBs).

The variable wrote_something is not about having written anything physically to disk but to the 608 buffer if I recall correctly. It shouldn't take the return of write()

Also this function is going to be executed many times:
caps = encode_sub(enc_ctx, dec_sub);

So caps can go from 1 to 0... however once subtitles have been written then the final output should be 0 (assuming we return 0 if subtitles were found and non-zero to signal no subs).

Making a note of this in the decoder is quite clever though, probably the best place to do it.

I'm closing this PR now since it's not ready for merging, but I'd say you are in the right direction.

**Comment by anukul** [comment]
Okay, thanks for taking a look at it. I'll work on fixing it.
Can you help me with the raw file issue? I can't seem to get a working raw input file for the program. :/

	$ ls

		ccextractor  inp.ts

	$ ./ccextractor inp.ts --hauppauge         

		CCExtractor 0.82, Carlos Fernandez Sanz, Volker Quetschke.
		Teletext portions taken from Petr Kutalek's telxcc
		--------------------------------------------------------------------------
		Input: inp.ts
		[Extract: 1] [Stream mode: Autodetect]
		[Program : Auto ] [Hauppage mode: Yes] [Use MythTV code: Auto]
		[Timing mode: Auto] [Debug: No] [Buffer input: No]
		[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
		[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
		[Add font color data: Yes] [Add font typesetting: Yes]
		[Convert case: No] [Video-edit join: No]
		[Extraction start time: not set (from start)]
		[Extraction end time: not set (to end)]
		[Live stream: No] [Clock frequency: 90000]
		[Teletext page: Autodetect]
		[Start credits text: None]

		-----------------------------------------------------------------
		Opening file: inp.ts
		File seems to be a transport stream, enabling TS mode
		Analyzing data in general mode
		Creating inp.srt
		100%  |  00:28
		Number of NAL_type_7: 0
		Number of VCL_HRD: 0
		Number of NAL HRD: 0
		Number of jump-in-frames: 0
		Number of num_unexpected_sei_length: 0

		Total frames time:	  00:00:00:000  (0 frames at 29.97fps)

		Min PTS:				02:59:04:743
		Max PTS:				02:59:33:472
		Length:				 00:00:28:729
		Done, processing time = 0 seconds
		This is beta software. Report issues to carlos at ccextractor org...

	$ wc -l inp.srt 

		45 inp.srt

	$ ./ccextractor inp.ts --hauppauge -out=raw

		CCExtractor 0.82, Carlos Fernandez Sanz, Volker Quetschke.
		Teletext portions taken from Petr Kutalek's telxcc
		--------------------------------------------------------------------------
		Input: inp.ts
		[Extract: 1] [Stream mode: Autodetect]
		[Program : Auto ] [Hauppage mode: Yes] [Use MythTV code: Auto]
		[Timing mode: Auto] [Debug: No] [Buffer input: No]
		[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
		[Target format: .raw] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
		[Add font color data: Yes] [Add font typesetting: Yes]
		[Convert case: No] [Video-edit join: No]
		[Extraction start time: not set (from start)]
		[Extraction end time: not set (to end)]
		[Live stream: No] [Clock frequency: 90000]
		[Teletext page: Autodetect]
		[Start credits text: None]

		-----------------------------------------------------------------
		Opening file: inp.ts
		File seems to be a transport stream, enabling TS mode
		Analyzing data in general mode
		Creating inp.raw
		100%  |  00:28
		Number of NAL_type_7: 0
		Number of VCL_HRD: 0
		Number of NAL HRD: 0
		Number of jump-in-frames: 0
		Number of num_unexpected_sei_length: 0

		Total frames time:	  00:00:00:000  (0 frames at 29.97fps)

		Min PTS:				02:59:04:743
		Max PTS:				02:59:33:472
		Length:				 00:00:28:729
		Done, processing time = 0 seconds
		This is beta software. Report issues to carlos at ccextractor org...

	$ tree

	.
	├── ccextractor
	├── inp.d
	├── inp.raw
	├── inp.srt
	└── inp.ts

	1 directory, 4 files

	$ cat inp.raw 

		����﻿<subpictures>
		<stream>
		
		</stream>
		</subpictures>

	$ ./ccextractor inp.raw     

		CCExtractor 0.82, Carlos Fernandez Sanz, Volker Quetschke.
		Teletext portions taken from Petr Kutalek's telxcc
		--------------------------------------------------------------------------
		Input: inp.raw
		[Extract: 1] [Stream mode: Autodetect]
		[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
		[Timing mode: Auto] [Debug: No] [Buffer input: No]
		[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
		[Target format: .srt] [Encoding: UTF-8] [Delay: 0] [Trim lines: No]
		[Add font color data: Yes] [Add font typesetting: Yes]
		[Convert case: No] [Video-edit join: No]
		[Extraction start time: not set (from start)]
		[Extraction end time: not set (to end)]
		[Live stream: No] [Clock frequency: 90000]
		[Teletext page: Autodetect]
		[Start credits text: None]

		-----------------------------------------------------------------
		Opening file: inp.raw
		File seems to be an elementary stream, enabling ES mode
		Analyzing data in general mode
		Creating inp.srt

		Number of NAL_type_7: 0
		Number of VCL_HRD: 0
		Number of NAL HRD: 0
		Number of jump-in-frames: 0
		Number of num_unexpected_sei_length: 0

		Total frames time:	  00:00:00:000  (0 frames at 29.97fps)
		Done, processing time = 0 seconds
		This is beta software. Report issues to carlos at ccextractor org...

	$ wc -l inp.srt 

		0 inp.srt

	$

**Comment by anukul** [comment]
How do I reopen this?
I've made a new commit in my repository.

**Pull request closed without merging**
