### PR TITLE
GCI: Updated README.md

### PR DESCRIPTION
**Pull request by TehTotalPwnage**
Updated the README.md as one of the tasks for the Google Code-in. I reorganized some of the sections of the README.md, provided more links to website documentation, added information about support, and patched up some of the grammar.

### CODE REVIEW

**Comment by yodadude2003** [comment]
anyone else notice that all of the pull requests fail in the same way?

**Comment by TehTotalPwnage** [comment]
It's probably an issue with one of the parts of the code. That should probably be fixed so that the checks stop failing.

**Comment by DanilaFe** [comment]
Looks like their tests are throwing a fit over slightly differently extracted captions.

**Comment by canihavesomecoffee** [comment]
Both of you are actually wrong on this one ;)

One 'error' is because a fix was committed for the DVB sample (so compared to the output of the last offcial version this is an 'error', as the goal of the tests is to show there's been no regression taking place). The other is somewhat more complex, and has been failing for a longer while.

If you want to help solve that last issue, you can take up this task: https://codein.withgoogle.com/dashboard/tasks/5673296855040000/

**Pull request merged**
