### PR TITLE
[IMPROVEMENT] Add Autoconf scripts to make CCExtractor more linux standard compliant

### PR DESCRIPTION
**Pull request by fandango-**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [x] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

---

This PR add autoconf scripts (mainly configure.ac and Makefile.am) to allow the standard configure / make / make install process for building and installing CCExtractor on Linux systems.

Makefile.am is mostly derived from the existing Makefile (removed in this PR as it is no longer required) with target renaming as appropriate.

All the lib checking (tesseract, leptonica, etc.) and option parsing (--enable-ocr, --enable-ffmpeg, etc.) is now moved to the configure step after the addition of relevant macros in configure.ac

The other files added (Makefile.in, config.h.in, etc.) allow the building and installation to take place on systems where autotools is not installed.

pre-build.sh was modified to use relative paths with respect to the directory in which the shell script exists and not the current build directory.

Tested on
Kernel		: Linux 4.4.48-1-MANJARO (x86_64)
C Library		: GNU C Library version 2.24 (stable)
Default C Compiler		: GNU C Compiler version 6.3.1 20170109 (GCC) 
Distribution		: Manjaro Linux

Part 1 of 3 to resolve Issue #678

### CODE REVIEW

**Comment by fandango-** [comment]
Thanks for the review. Okay, I've removed the autogenerated scripts. Also, I've added a bootstrap script to generate the configure file using the autotools commands.

So, new flow for building and installing would be:
$ ./bootstrap
$ ./configure
$ make
$ sudo make install

**Comment by rkuchumov** [comment]
seems that package generated with `make dist` doesn't work. And don't forget to update .gitignore

**Comment by fandango-** [comment]
Yes, thanks for noting the issue. 'make dist' now works - it generates a .tar.gz file with all the required files. However, 'make distcheck' will fail as it expects configure in the topmost directory. Currently, the tar archive generated has 2 subfolders with the ccextractor-0.85 folder - linux and src. The configure is actually in the linux directory. So, to test it out:
$ make dist
$ tar -xvf tar -xvf ccextractor-0.85.tar.gz
$ cd ccextractor-0.85/linux/
$ ./configure
$ make
$ sudo make install

Also, the .gitignore was updated.

**Comment by rkuchumov** [comment]
when I do 
```
./bootstrap
./configure --prefix=/home/rk/.local/bin/
make install -j4
```
it still tries to copy executable to `/usr/bin/` instead of my local folder. `--exec-copy` didn't help as well.

**Comment by cfsmp3** [comment]
Closing because an alternative PR has been merged, you still get GSoC points for the work.

**Pull request closed without merging**
