### PR TITLE
[FIX] Attempt to fix long-running regression in TeleText

### PR DESCRIPTION
**Pull request by canihavesomecoffee**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.
- [x] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [x] I am an active contributor to CCExtractor.

Regression test 78 (https://sampleplatform.ccextractor.org/regression/test/78/view)
has been broken since #622 was merged to fix other issues.

It's been traced back to be caused by not setting t0 at the correct time
(setting it using a calculated PTS time rather than taking it from the video frame),
and this commits attempts to fix that.

### CODE REVIEW

**Review by cfsmp3 — COMMENTED** [review]
Let's call this possibly passable :-)
Feel free to merge if the SP is happy with it.

**Review by alexbrt — APPROVED** [review]
As long as everything else is still in order, this looks good to me!

**Comment by canihavesomecoffee** [comment]
> As long as everything else is still in order, this looks good to me!

Unfortunately it isn't :P

Timing's off by ~10 minutes, so I'll have to dig a bit further.

**Comment by alexbrt** [comment]
I'll take a look at it myself these days, maybe 15yo @alexbrt omitted something in that PR :p

**Comment by canihavesomecoffee** [comment]
@alexbrt @cfsmp3 I fixed it in a more simple way, using the current_pts rather than a fixed min_pts. This should only affect TT anyway, but I'm not sure if it'll break things Alex fixed...

Now it's just a difference of ~0.02s, due to it taking the PTS from the previous frame (new code) rather than the next (old code). This seems acceptable to me.

**Comment by cfsmp3** [comment]
I suspect it will break multiprogram transport streams but I could be mistaken

**Comment by canihavesomecoffee** [comment]
No regressions noticed when testing with Closedcaption_atsc_multiprog.ts (using `-out=srt -pn 2` with varying pn)

**Pull request merged**
