### PR TITLE
[FEAT] Use system gpac library instead of vendoring gpacmp4

### PR DESCRIPTION
**Pull request by prateekmedia**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.
- [ ] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [x] I am an active contributor to CCExtractor.

---

Vendoring gpac has numerous issues like updating regulary and on homebrew they like to have gpac as a separate library

This PR removes gpacmp4 and instead uses the system installed version of gpac.

Additionally this PR fixes the ccextractor build on mac os for all types like `cmake`, `make` or using `build.command` executable file (I will add Mac CI in another PR)

Working Status:
- [x] Linux (sample platform needs to be updated and added libgpac-dev as a build dependency)
- [x] Mac
- [x] Windows

### CODE REVIEW

**Comment by prateekmedia** [comment]
@cfsmp3 @canihavesomecoffee The errors in sample platform are also present in master, so I think this PR is ready to merge.

**Comment by cfsmp3** [comment]
> @cfsmp3 @canihavesomecoffee The errors in sample platform are also present in master, so I think this PR is ready to merge.

I don't have a problem with the PR, but I think we should prioritize getting the test platform working so we can actually trust PRs based on things working, not on things failing equally :-)

**Comment by prateekmedia** [comment]
@cfsmp3 @canihavesomecoffee All CI tests are passing, don't know about sample platform ones.

**Comment by canihavesomecoffee** [comment]
@prateekmedia There's one test on Linux that I'm a bit worried about: MP4 (RT 237) is failing, while the last master succeeded. All subs seem to be gone. Giving we're moving from gpacmp4 to gpac this seems to be related.

**Comment by prateekmedia** [comment]
@canihavesomecoffee Don't know why it was not detected, but it was also happening in previous release, logs below:
```
Detected MP4 box with name: ftyp
Detected MP4 box with name: moov
File seems to be a MP4
Analyzing data with GPAC (MP4 library)
Opening '../8849331ddae9c3169024d569ce17b9a4fdd917401cd6c6bfb8dc1fd59c6af21e.mp4': [iso file] Read Box type 00000000 (0x00000000) at position 702276 has size 0 but is not at root/file level, skipping
[iso file] Box "c608" (start 692180) has 28 extra bytes
ok
Track 1, type=vide subtype=avc1
Track 2, type=soun subtype=MPEG
Track 3, type=clcp subtype=c608
MP4: found 3 tracks: 1 avc and 1 cc
Processing track 1, type=vide subtype=avc1
Processing track 2, type=soun subtype=MPEG
Processing track 3, type=clcp subtype=c608
100%  |  22:30
Closing media: ok
Found 1 AVC track(s). Found 1 CC track(s).


Total frames time:	  00:00:00:000  (0 frames at 29.97fps)

Min PTS:				00:00:00:000
Max PTS:				00:22:30:882
Length:				 00:22:30:882
Done, processing time = 0 seconds
Issues? Open a ticket here
https://github.com/CCExtractor/ccextractor/issues
```

**Review by canihavesomecoffee — APPROVED** [review]
LGTM after investigating that one sample manually.

**Comment by utkarsh2102** [comment]
This was a wonderful effort, thank you for doing this.

**Pull request merged**
