### PR TITLE
Case fix

### PR DESCRIPTION
**Pull request by mailumangjain**
Case fix.
Base sample : /John(lowercase)

### CODE REVIEW

**Comment by wforums** [comment]
I think that the case fixing should be optional, now it will always be applied. For regular captions we have the -sc (--sentencap) parameter. I'd propose to use this one (and add an option to the telxcc code to make use of it) to let the user decide if he wants the case formatting yes or no.

If this is not done, regression testing will need to be done.

**Comment by wforums** [comment]
@mailumangjain: could you add support for the -sc parameter? You can borrow the code I have for it (see: https://github.com/wforums/ccextractor/commit/d539ee9109a8adc9df8b0c9ea1d9cd4c1e51b2ab) :smile:

**Comment by mailumangjain** [comment]
Oh yes @wforums ! just give me some time, I'll do it as soon as possible and notify here ! Thanks for the help. :)

**Comment by mailumangjain** [comment]
@wforums I have added -sc parameter for capitalization choice by user.

**Comment by cfsmp3** [comment]
Why use a different config variable? Rather than adding a variable
in tlt_config just use the same one used in the rest of the code.

**Comment by wforums** [comment]
the ccx options are not available in the tlt config (anymore), that's the reason it has a new variable in tlt_config.

**Comment by wforums** [comment]
While the outdated version of @mailumangjain still might contain ccx_options, it is in our current git repo not longer the case. @anshul1912 refactored this a while ago, hence the need for the extra variable.

**Comment by anshul1912** [comment]
something that is need to be done  is teletext should use encoder interface, if it use same encoder interface then there is no need of that variable, same variable can be used.
If someone is going for workaround then he dont need to add any new global variable, instead paas global variable to tlt_config

**Comment by anshul1912** [comment]
I have passed cc_sub structure inside, using it telexcc no more need any local configuration for output

**Comment by wforums** [comment]
@mailumangjain Would it be possible for you to close this request, update CCExtractor and make a new (unconflicting) PR? I tried a merge, but it seems as though a couple of regression files are affected by the change... http://gsocdev.ccextractor.org/~willem/users/willem/Testsuite_Report_2015-06-18_115417/Report__Teletext_2015-06-18_120038.html

**Comment by mailumangjain** [comment]
ok. I was waiting for cc_sub to be passed.
Can anyone brief me about how regression testing/ @wforums testSuite works so that I can myself try and find if my solution is correct, in future ?

**Comment by wforums** [comment]
Regression testing is at this moment only possible if you have an account on the development server, or if you can download the testing suite and all the samples. I'm planning to improve this, but in the meantime, I'll gladly run the test suite for you if you think you have a solution ready :)

**Comment by mailumangjain** [comment]
Well, Thank you. Just being curious :)

On Thu, Jun 18, 2015 at 6:22 PM, Willem <notifications@github.com> wrote:

> Regression testing is at this moment only possible if you have an account
> on the development server, or if you can download the testing suite and all
> the samples. I'm planning to improve this, but in the meantime, I'll gladly
> run the test suite for you if you think you have a solution ready :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CCExtractor/ccextractor/pull/173#issuecomment-113146723>
> .
>



-- 
Umang Jain

**Comment by anshul1912** [comment]
"I was waiting for cc_sub to be passed."
@mailumangjain  I have passed them already, git pull your repository

**Comment by mailumangjain** [comment]
I added a "int sent_cap" in cc_sub struct for managing capitalization. I handled the cases if users wants capitalization.
My question is where do I set the variable value for "int sent_cap" when the user passes -sc parameter.
I am looking in params.c , but there is no cc_sub structure reference present there ? Am i doing something wrong ?

**Pull request closed without merging**
