### PR TITLE
[FEAT] Add timing module in `lib_ccxr`

### PR DESCRIPTION
**Pull request by IshanGrover2004**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.
- [x] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [x] I am an active contributor to CCExtractor.

---

Closes #1558

This PR adds types and functions to store and calculate timing related information during the decoding process. The functions are integrated into C. 
After this PR merge, `ccx_common_timing.c` & `ccx_common_timing.h` file is completed ported to rust

### CODE REVIEW

**Comment by IshanGrover2004** [comment]
@prateekmedia Can you just run `cargo clippy -- -D warnings` in `parser.rs`

**Comment by IshanGrover2004** [comment]
@PunitLodha You can review the PR

**Comment by IshanGrover2004** [comment]
For the Windows build CI failing,
Here is the reason:
image

Its weird, now how can I possibly fix it...?

**Comment by PunitLodha** [comment]
@IshanGrover2004 could you fix the conflict?

**Review by PunitLodha — APPROVED** [review]

**Comment by IshanGrover2004** [comment]
@PunitLodha I think you can merge this, this PR is fine ig

**Pull request merged**
