### PR TITLE
add WebVTT support

### PR DESCRIPTION
**Pull request by december-soul**
add support for output format WebVTT.
Needed for html5 video player

### CODE REVIEW

**Comment by wforums** [comment]
@ccx-testerbot runtests master

**Comment by wforums** [comment]
@ccx-testerbot runtests master

**Comment by wforums** [comment]
@ccx-testerbot runtests master

@december-soul Sorry for using this commit to test some things!

**Comment by wforums** [comment]
@ccx-testerbot runtests master

**Comment by wforums** [comment]
@ccx-testerbot runtests master

**Comment by wforums** [comment]
@december-soul Looks like your pull request didn't break anything else that is [currently not already broken](https://github.com/CCExtractor/ccextractor/commit/f3654174fc568deb31e9bf4df1a55fef58cc7b67#commitcomment-12236796), nice work :+1:

**Comment by cfsmp3** [comment]
@december-soul <https://github.com/december-soul> could you send an update
pull request? There's merge conflicts with the current branch

**Comment by scramatte** [comment]
Please merge the branch +1

**Pull request closed without merging**
